### PR TITLE
Create denojs.md

### PR DESCRIPTION
**Pull request by leJad**
## What type of PR is this? (check all applicable)

- [x] Added new link to category
- [ ] New category added
- [ ] Fixed broken link
- [ ] Typo fix
- [ ] Readme update
- [ ] Optimization
- [x] Documentation update
- [ ] Frontend update

## Description

After creating the denojs.md file, I added some resources in it, added resources to the php.md and ruby-on-rails.md files, and edited the sidebar.js file

## [optional] Related Issues & Documents

- #14

### CODE REVIEW

**Review by YusufBilgin — APPROVED** [review]
👍

**Comment by damla** [comment]
@leJad açıklama kısmını doldurabilir misin?

**Comment by leJad** [comment]
> @leJad açıklama kısmını doldurabilir misin?

Done

**Review by damla — APPROVED** [review]
lgtm 👍🏼

**Pull request merged**
